### PR TITLE
add support for awesome-git

### PR DESCRIPTION
**Pull request by aarondill**
This PR makes the widget work on awesome's HEAD.

### CODE REVIEW

**Comment by aarondill** [comment]
I've tested this on `v4.3` and github.com/awesomewm/awesome/commit/0e5fc4575ab0adbae75908cb49937d9cf63437ec.

Note: you might try to consolidate this
```lua
if self.widget.set_halign then
    self.widget.set_halign('right')
else
    self.widget.set_align("right")
end
```

to this:
```lua 
(self.widget.set_halign or self.widget.set_align)("right")
```

but it causes an error. Something about metatables that I can't quite figure out.

**Comment by aarondill** [comment]
@coldfix I originally removed the `if naughty` check, because the `require('naughty')` should throw if naughty is not available. Perhaps it should be changed to `pcall(require, 'naughty')` if you'd like to check the availability of the naughty module?
anyways, I will return the check. Let me know if you'd like it to be further modified.

**Comment by aarondill** [comment]
@coldfix I've addressed all your feedback

**Comment by coldfix** [comment]
> @coldfix I've addressed all your feedback

Great, thanks!

> @coldfix I originally removed the `if naughty` check, because the `require('naughty')` should throw if naughty is not available. Perhaps it should be changed to `pcall(require, 'naughty')` if you'd like to check the availability of the naughty module? anyways, I will return the check. Let me know if you'd like it to be further modified.

Hm, I think there was a good reason for this check. I agree that normally you wouldn't expect a falsy return if the module is not installed at all, but the module might `return nil` under certain circumstances. I would leave it in for now, it doesn't hurt.

**Comment by coldfix** [comment]
I guess you're right, I quickly checked over the awesome sources and I didn't see anything indicating that the `if naughty` check would be useful (neither the pcall, as naughty is distributed with awesome/lib itself).

**Pull request merged**
